[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
site_url = "http://localhost:5175/auth/setup-password"
additional_redirect_urls = [
  "http://localhost:5173/**",
  "http://localhost:5174/**",
  "http://localhost:5175/**"
]
